# JWT_SECRET=R@&&1HTrzVYVXQ*7N*wZBSDIhCutJ&ld$#as9db31ulUTKWW6QzZfd5Tj0xLZM%7gB4wqFHwLvtL6z*muIzAIieLvVeW9lRy@AP$

apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
data:
  JWT_SECRET: UkAmJjFIVHJ6VllWWFEqN04qd1pCU0RJaEN1dEombGQkI2FzOWRiMzF1bFVUS1dXNlF6WmZkNVRqMHhMWk0lN2dCNHdxRkh3THZ0TDZ6Km11SXpBSWllTHZWZVc5bFJ5QEFQJA==
