apiVersion: v1
kind: Service
metadata:
  name: analytics-for-links-and-sites
spec:
  selector:
    app: analytics-for-links-and-sites
    type: web
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-for-links-and-sites
spec:
  selector:
    matchLabels:
      app: analytics-for-links-and-sites
      type: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: analytics-for-links-and-sites
        type: web
    spec:
      containers:
      - name: analytics-for-links-and-sites
# Set version here
        image: kellenschmidt/analytics-for-links-and-sites:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
