apiVersion: v1
kind: Service
metadata:
  name: dqc-web
spec:
  selector:
    app: data-quality-checker
    type: web
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dqc-web
spec:
  selector:
    matchLabels:
      app: data-quality-checker
      type: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: data-quality-checker
        type: web
    spec:
      containers:
      - name: dqc-web
# Set version here
        image: kellenschmidt/kspw-dqc:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 80
