apiVersion: v1
kind: Service
metadata:
  name: interactive-resume-and-url-shortener
spec:
  selector:
    app: interactive-resume
    type: web
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interactive-resume-and-url-shortener
spec:
  selector:
    matchLabels:
      app: interactive-resume
      type: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: interactive-resume
        type: web
    spec:
      containers:
      - name: interactive-resume-and-url-shortener
# Set version here
        image: kellenschmidt/interactive-resume-and-url-shortener:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
