apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  selector:
    app: metabase
    type: console
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  selector:
    matchLabels:
      app: metabase
      type: console
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metabase
        type: console
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
        - containerPort: 80
