apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    type: console
spec:
  ports:
  - port: 80
  selector:
    app: phpmyadmin
    type: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
      type: console
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
        type: console
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "mysql"
        - name: PMA_VERBOSE
          value: "mysql"
        - name: PMA_PORT
          value: "3306"
