apiVersion: v1
kind: Service
metadata:
  name: slimphp-api
spec:
  selector:
    app: url-shortener
    type: api
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slimphp-api
spec:
  selector:
    matchLabels:
      app: url-shortener
      type: api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: url-shortener
        type: api
    spec:
      containers:
      - name: slimphp-api
# Set version here
        image: kellenschmidt/slimphp-api:latest
        imagePullPolicy: Always
        env:
        - name: MYSQL_HOST
          value: "mysql:3306"
        envFrom:
        - secretRef:
            name: mysql-login
        - secretRef:
            name: jwt
        ports:
        - containerPort: 80
